/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: [
    './src/**/*.{vue,js,ts,jsx,tsx}',
    '../../packages/**/*.{vue,js,ts,jsx,tsx}',
    '../../apps/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          primary800: 'var(--base-colors-primary-primary800)',
          primary700: 'var(--base-colors-primary-primary700)',
          primary600: 'var(--base-colors-primary-primary600)',
          primary500: 'var(--base-colors-primary-primary500)',
          primary400: 'var(--base-colors-primary-primary400)',
          primary300: 'var(--base-colors-primary-primary300)',
          primary200: 'var(--base-colors-primary-primary200)',
          primary100: 'var(--base-colors-primary-primary100)',
          primary050: 'var(--base-colors-primary-primary050)',
          'primary-deep': 'var(--base-colors-primary-primary-deep)',
        },
        neutral: {
          neutral800: 'var(--base-colors-neutral-neutral800)',
          neutral700: 'var(--base-colors-neutral-neutral700)',
          neutral600: 'var(--base-colors-neutral-neutral600)',
          neutral500: 'var(--base-colors-neutral-neutral500)',
          neutral400: 'var(--base-colors-neutral-neutral400)',
          neutral300: 'var(--base-colors-neutral-neutral300)',
          neutral200: 'var(--base-colors-neutral-neutral200)',
          neutral100: 'var(--base-colors-neutral-neutral100)',
          neutral000: 'var(--base-colors-neutral-neutral000)',
          neutral750: 'var(--base-colors-neutral-neutral750)',
          neutral250: 'var(--base-colors-neutral-neutral250)',
          neutral150: 'var(--base-colors-neutral-neutral150)',
          neutral550: 'var(--base-colors-neutral-neutral550)',
          neutral050: 'var(--base-colors-neutral-neutral050)',
        },
        green: {
          green100: 'var(--base-colors-green-green100)',
          green200: 'var(--base-colors-green-green200)',
          green300: 'var(--base-colors-green-green300)',
          green400: 'var(--base-colors-green-green400)',
          green600: 'var(--base-colors-green-green600)',
          green700: 'var(--base-colors-green-green700)',
          green500: 'var(--base-colors-green-green500)',
          green800: 'var(--base-colors-green-green800)',
          green050: 'var(--base-colors-green-green050)',
        },
        red: {
          red800: 'var(--base-colors-red-red800)',
          red700: 'var(--base-colors-red-red700)',
          red600: 'var(--base-colors-red-red600)',
          red500: 'var(--base-colors-red-red500)',
          red400: 'var(--base-colors-red-red400)',
          red300: 'var(--base-colors-red-red300)',
          red200: 'var(--base-colors-red-red200)',
          red100: 'var(--base-colors-red-red100)',
          red050: 'var(--base-colors-red-red050)',
        },
        blue: {
          'blue800-deep': 'var(--base-colors-blue-blue800-deep)',
          blue700: 'var(--base-colors-blue-blue700)',
          blue600: 'var(--base-colors-blue-blue600)',
          blue500: 'var(--base-colors-blue-blue500)',
          blue400: 'var(--base-colors-blue-blue400)',
          blue300: 'var(--base-colors-blue-blue300)',
          blue200: 'var(--base-colors-blue-blue200)',
          blue100: 'var(--base-colors-blue-blue100)',
          blue050: 'var(--base-colors-blue-blue050)',
          blue800: 'var(--base-colors-blue-blue800)',
        },
        common: {
          'bg-surface-default': 'var(--base-colors-common-bg-surface-default)',
          'light-gray-ca': 'var(--base-colors-common-light-gray-ca)',
          'light-gray-f5': 'var(--base-colors-common-light-gray-f5)',
          'light-gray-ea': 'var(--base-colors-common-light-gray-ea)',
          'bg-surface-dark': 'var(--base-colors-common-bg-surface-dark)',
        },
        purple: {
          purple800: 'var(--base-colors-purple-purple800)',
          purple700: 'var(--base-colors-purple-purple700)',
          purple600: 'var(--base-colors-purple-purple600)',
          purple500: 'var(--base-colors-purple-purple500)',
          purple400: 'var(--base-colors-purple-purple400)',
          purple300: 'var(--base-colors-purple-purple300)',
          purple200: 'var(--base-colors-purple-purple200)',
          purple100: 'var(--base-colors-purple-purple100)',
          purple050: 'var(--base-colors-purple-purple050)',
        },
        input: {
          surface: 'var(--input-color-surface)',
          'border-static': 'var(--input-color-border-static)',
          'border-focus': 'var(--input-color-border-focus)',
          'border-error': 'var(--input-color-border-error)',
          'border-disabled': 'var(--input-color-border-disabled)',
          'text-placeholder': 'var(--input-color-text-placeholder)',
          'text-disable': 'var(--input-color-text-disable)',
          'text-static': 'var(--input-color-text-static)',
          'bg-disabled': 'var(--input-color-bg-disabled)',
        },
        'bg-bg-default': 'var(--background-bg-default)',
        'bg-bg-surface': 'var(--background-bg-surface)',
        'bg-bg-outline': 'var(--background-bg-outline)',
        'bg-bg-surface-muted': 'var(--background-bg-surface-muted)',
        'bg-divider': 'var(--background-divider)',
        'bg-divider-muted': 'var(--background-divider-muted)',
        'bg-bg-innerframe': 'var(--background-bg-innerframe)',
        'bg-primary': 'var(--background-primary)',
        'bg-primary-light': 'var(--background-primary-light)',
        'bg-bg-surface-dark': 'var(--background-bg-surface-dark)',
      },
      textColor: {
        primary: 'var(--font-color-primary)',
        default: 'var(--font-color-default)',
        'default-muted': 'var(--font-color-default-muted)',
        red: 'var(--font-color-red)',
        buy: 'var(--font-color-buy)',
        sell: 'var(--font-color-sell)',
        white: 'var(--font-color-white)',
        black: 'var(--font-color-black)',
        blue: 'var(--font-color-blue)',
        footer: 'var(--font-color-footer)',
        'default-muted-dark': 'var(--font-color-default-muted-dark)',
        green: 'var(--font-color-green)',
        purple: 'var(--font-color-purple)',
      },
      fontSize: {
        'font-36': 'var(--font-size-font-36)',
        'font-24': 'var(--font-size-font-24)',
        'font-13': 'var(--font-size-font-13)',
        'font-20': 'var(--font-size-font-20)',
        'font-14': 'var(--font-size-font-14)',
        'font-64': 'var(--font-size-font-64)',
        'font-48': 'var(--font-size-font-48)',
        'font-12': 'var(--font-size-font-12)',
        'font-18': 'var(--font-size-font-18)',
        'font-16': 'var(--font-size-font-16)',
        'font-10': 'var(--font-size-font-10)',
      },
      lineHeight: {
        0: 'var(--font-line-heights-0)',
        1: 'var(--font-line-heights-1)',
        2: 'var(--font-line-heights-2)',
        3: 'var(--font-line-heights-3)',
        4: 'var(--font-line-heights-4)',
        5: 'var(--font-line-heights-5)',
        6: 'var(--font-line-heights-6)',
        7: 'var(--font-line-heights-7)',
        8: 'var(--font-line-heights-8)',
      },
      letterSpacing: {
        0: 'var(--font-letter-spacing-0)',
        1: 'var(--font-letter-spacing-1)',
        2: 'var(--font-letter-spacing-2)',
        3: 'var(--font-letter-spacing-3)',
        4: 'var(--font-letter-spacing-4)',
        5: 'var(--font-letter-spacing-5)',
      },
      spacing: {
        'size-14': 'var(--base-size-size-14)',
        'size-13': 'var(--base-size-size-13)',
        'size-10': 'var(--base-size-size-10)',
        'size-8': 'var(--base-size-size-8)',
        'size-16': 'var(--base-size-size-16)',
        'size-6': 'var(--base-size-size-6)',
        'size-300': 'var(--base-size-size-300)',
        'size-12': 'var(--base-size-size-12)',
        'size-64': 'var(--base-size-size-64)',
        'size-130': 'var(--base-size-size-130)',
        'size-200': 'var(--base-size-size-200)',
        'size-4': 'var(--base-size-size-4)',
        'size-140': 'var(--base-size-size-140)',
        'size-48': 'var(--base-size-size-48)',
        'size-18': 'var(--base-size-size-18)',
        'size-36': 'var(--base-size-size-36)',
        'size-24': 'var(--base-size-size-24)',
        'size-20': 'var(--base-size-size-20)',
        'size-round': 'var(--base-size-size-round)',
        'size-100': 'var(--base-size-size-100)',
        'size-0': 'var(--base-size-size-0)',
        'size-40': 'var(--base-size-size-40)',
        'size-50': 'var(--base-size-size-50)',
        'size-88': 'var(--base-size-size-88)',
        'padding-64': 'var(--padding-padding-64)',
        'padding-48': 'var(--padding-padding-48)',
        'padding-36': 'var(--padding-padding-36)',
        'padding-16': 'var(--padding-padding-16)',
        'padding-24': 'var(--padding-padding-24)',
        'padding-12': 'var(--padding-padding-12)',
        'padding-4': 'var(--padding-padding-4)',
        'padding-130': 'var(--padding-padding-130)',
        'padding-8': 'var(--padding-padding-8)',
        'padding-z': 'var(--padding-padding-z)',
        'padding-88': 'var(--padding-padding-88)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
        default: 'var(--radius-default)',
        none: 'var(--radius-none)',
      },
    },
  },
};
