# OpenAPI Generator 설정 파일
# TypeScript Axios 클라이언트 생성을 위한 설정

# 생성기 설정
generatorName: typescript-axios

# 기본 설정
additionalProperties:
  # 패키지 정보
  npmName: "@template/api-generated"
  npmVersion: "1.0.0"
  npmDescription: "Generated API client for @template/api"
  
  # TypeScript 설정
  typescriptThreePlus: true
  supportsES6: true
  useSingleRequestParameter: true
  withInterfaces: true
  stringEnums: true
  enumPropertyNaming: "original"
  
  # Axios 설정
  useAxios: true
  withNodeImports: false
  withSeparateModelsAndApi: true
  
  # 코드 품질
  modelPropertyNaming: "camelCase"
  enumPropertyNaming: "original"
  parameterNaming: "camelCase"
  
  # 파일 구조
  modelPackage: "models"
  apiPackage: "apis"
  packageName: "generated"
  
  # 기타 설정
  sortParamsByRequiredFlag: true
  ensureUniqueParams: true
  allowUnicodeIdentifiers: false
  prependFormOrBodyParameters: true
  
  # 한국어 지원
  dateLibrary: "date-fns"
  
  # Tree shaking 지원
  useES6: true
  useInversify: false
  
  # 타입 안전성
  disallowAdditionalPropertiesIfNotPresent: false
  typeMappings:
    DateTime: "Date"
    date: "Date"
    time: "Date"
  
  # import 설정
  importMappings:
    DateTime: "date-fns"
    date: "date-fns"
    time: "date-fns"

# 글로벌 속성
globalProperties:
  # 모델 설정
  models: ""
  apis: ""
  supportingFiles: ""
  
  # API 문서화
  apiDocs: false
  modelDocs: false
  
  # 테스트 파일 생성
  apiTests: false
  modelTests: false

# 템플릿 디렉토리 (커스터마이징용)
templateDir: "openapi-templates/typescript-axios"

# 출력 파일 필터링
importMappings: {}

# 타입 매핑
typeMappings:
  DateTime: "Date"
  date: "Date"
  time: "Date"

# 언어별 설정
languageSpecificPrimitives:
  - "string"
  - "boolean"
  - "number"
  - "Date"
  - "Array"
  - "Object"
  - "any"

# 제외할 파일들
excludeFiles: []

# 포함할 파일들
includeFiles: []

# 추가 모델 속성
additionalModelTypeAnnotations: []

# 추가 API 속성
additionalApiTypeAnnotations: []

# 환경 변수 설정
environmentVariables:
  NODE_TLS_REJECT_UNAUTHORIZED: "0"

# 보안 설정
securitySchemes:
  bearerAuth:
    type: "http"
    scheme: "bearer"
    bearerFormat: "JWT"

# 서버 설정
servers:
  - url: "http://localhost:3000"
    description: "Development server"
  - url: "https://api.example.com"
    description: "Production server"

# 응답 설정
responseHeaders: []

# 요청 설정
requestHeaders: []

# 파일 업로드 설정
fileUploadOptions:
  maxFileSize: "10MB"
  allowedMimeTypes:
    - "image/*"
    - "application/pdf"
    - "text/*"

# 로깅 설정
logging:
  level: "info"
  format: "json"

# 캐싱 설정
caching:
  enabled: true
  ttl: 300

# 재시도 설정
retry:
  maxAttempts: 3
  backoffMultiplier: 2
  maxDelay: 10000

# 타임아웃 설정
timeout:
  request: 30000
  response: 30000

# 압축 설정
compression:
  enabled: true
  algorithm: "gzip"

# 인증 설정
authentication:
  type: "bearer"
  tokenEndpoint: "/auth/token"
  refreshEndpoint: "/auth/refresh"

# 에러 처리 설정
errorHandling:
  throwOnError: true
  logErrors: true
  includeStackTrace: false

# 성능 모니터링
monitoring:
  enabled: true
  metrics:
    - "request_duration"
    - "request_count"
    - "error_rate"

# 개발 도구 설정
development:
  hotReload: true
  sourceMaps: true
  debugMode: false

# 프로덕션 설정
production:
  minify: true
  optimize: true
  bundleAnalysis: true
