packages:
  - 'apps/*'
  - 'packages/*'
  - 'shared'

# 공통 devDependencies를 루트로 hoisting
pnpm:
  overrides:
    vitest: ^1.6.1
    react: ^19.1.1
    react-dom: ^19.1.1
    '@types/react': ^19.1.1
  nodeVersion: '>=20.0.0'
