/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface AccountCreateRequest {
  /** 계좌 비밀번호 */
  accountPassword: string;
  /** 계좌 별칭 */
  accountAlias?: string;
}



export interface AccountCreateResponse {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌순번 */
  accountSequence: string;
  /** 표시순번 */
  visibleSequence: string;
}



export interface AccountInfo {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌순번 */
  accountSequence: string;
  /** 등급그룹코드 */
  accountGrade: string;
  /** 계좌별칭 */
  accountAlias: string;
  /** 표시여부 */
  visible: string;
  /** 표시순번 */
  visibleSequence: string;
}



export interface AccountInfoResponse {
  /** 계좌 리스트 */
  accountList: Array<AccountInfo>;
}



export interface AccountInfoUpdateRequest {
  /** 계좌 정보 목록 */
  accountInfos: Array<ItemDto>;
}



export interface AccountUpdatePwdRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 변경 전 비밀번호 */
  beforeAccountPassword: string;
  /** 변경 후 비밀번호 */
  afterAccountPassword: string;
}



export interface ItemDto {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌별칭 */
  accountAlias: string;
  /** 표시여부 */
  visible: string;
}



export interface ResponseDataAccountCreateResponse extends ApiSuccessResponse<AccountCreateResponse> {}



export interface ResponseDataAccountInfoResponse extends ApiSuccessResponse<AccountInfoResponse> {}

