/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface AssetDepositsRequest {
  /** 계좌번호 */
  accountNo: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface AssetDepositsResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 보유 포지션 정보 */
  positions?: Array<AssetPosition>;
  /** 보유 주문 구성 */
  summary?: Array<AssetOrder>;
}

export interface AssetPositionsRequest {
  /** 계좌번호 */
  accountNo: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface AssetPositionsResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 보유 포지션 정보 */
  positions: Array<Position>;
  /** 자산 구성 */
  summary?: Array<AssetSummary>;
}

export interface AssetOrder {
  /** 종목코드 */
  stockCd: string;
  /** 포지션구분코드 */
  positionCd: string;
  /** 매매구분코드 */
  sideCd: string;
  /** 주문수량 */
  orderQuantity: number;
  /** 배리어가격 */
  barrierPrice: number;
  /** 주문가격 */
  orderPrice: number;
  /** 주문증거금 */
  orderDepositPrice: number;
}

export interface AssetPosition {
  /** 종목코드 */
  stockCd: string;
  /** 포지션구분코드 */
  positionCd: string;
  /** 장부수량 */
  accountBookQuantity: number;
  /** 장부가격 */
  accountBookPrice: number;
  /** 포지션증거금 */
  depositPrice: number;
  /** 평가손익 */
  assessmentProfitLoss: number;
  /** 증거금율 */
  depositPercent: number;
}

export interface AssetSummary {
  /** 종목코드 */
  stockCd: string;
  /** 포지션구분코드 */
  positionCd: string;
  /** 포지션구분명 */
  positionName: string;
  /** 현재가 */
  currentPrice: number;
  /** 수익률 */
  reLongExecutionPrice: number;
  /** 비중 */
  ratePercent: number;
}

export interface Position {
  /** 종목코드 */
  stockCd: string;
  /** 거래통화코드 */
  tradeCurrencyCd: string;
  /** 포지션구분코드 */
  positionCd: string;
  /** 포지션구분명 */
  positionName: string;
  /** 장부수량 */
  accountBookQuantity: number;
  /** 청산가능수량 */
  liquidationPossibleQuantity: number;
  /** 장부가격 */
  accountBookPrice: number;
  /** 현재가 */
  currentPrice: number;
  /** 평가손익 */
  assessmentProfitLoss: number;
  /** 수익률 */
  reLongExecutionPrice: number;
}

export interface ResponseDataAssetDepositsResponse
  extends ApiSuccessResponse<AssetDepositsResponse> {}

export interface ResponseDataAssetPositionsResponse
  extends ApiSuccessResponse<AssetPositionsResponse> {}
