/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';
import { AccountInfo } from './account.types';
import { Email } from './common.types';

export interface AuthLoginRequest {
  /** */
  email: Email;
  /** 회원 비밀번호 */
  password?: string;
}



export interface AuthLoginResponse {
  /** 회원 ID */
  memberId: number;
  /** */
  email: Email;
  /** 회원 유형 */
  memberType: AuthLoginResponseMemberType;
  /** 계좌 리스트 */
  accountList: Array<AccountInfo>;
  /** */
  tokenInfo: TokenResponse;
}

/**
 * @export
 */
export type AuthLoginResponseMemberType = 'INDIVIDUAL' | 'CORPORATE';




export interface AuthRefreshTokenRequest {
  /** 만료된 AccessToken */
  expiredAccessToken: string;
}



export interface VerificationRequest {
  /** */
  email: Email;
  /** 인증 용도 */
  useType: VerificationRequestUseType;
}

/**
 * @export
 */
export type VerificationRequestUseType = 'SIGN_UP' | 'RESET_PASSWORD' | 'FIND_ID';




export interface VerificationCodeRequest {
  /** */
  email: Email;
  /** 6자리 숫자 인증 코드 */
  verificationCode: string;
  /** 인증 용도 */
  useType: VerificationCodeRequestUseType;
}

/**
 * @export
 */
export type VerificationCodeRequestUseType = 'SIGN_UP' | 'RESET_PASSWORD' | 'FIND_ID';




export interface ResponseDataAuthLoginResponse extends ApiSuccessResponse<AuthLoginResponse> {}



export interface ResponseDataTokenResponse extends ApiSuccessResponse<TokenResponse> {}



export interface TokenResponse {
  /** */
  accessToken: string;
  /** */
  refreshToken?: string;
}

