/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface ResponseDataObject {
  /** status */
  status: string;
  /** code */
  code: number;
  /** data */
  data?: object;
}

export interface ResponseDataString {
  /** status */
  status: string;
  /** code */
  code: number;
  /** data */
  data?: string;
}

export interface PageRequest {
  /** */
  page: number;
  /** */
  size: number;
  /** */
  sort?: string;
}

export interface Email {
  /** */
  value: string;
}

export interface StockCode {
  /** */
  value: string;
}

export interface OrderResponseDto {
  /** */
  trCode: string;
  /** */
  trGb: string;
  /** */
  handle: string;
  /** */
  copCd: string;
  /** */
  empNo: string;
  /** */
  grdGrcd: string;
  /** */
  userIp: string;
  /** */
  dataGrp: string;
  /** */
  user: string;
  /** */
  rcnt: number;
  /** */
  items?: Array<OrderResponseItemDto>;
}

export interface OrderResponseItemDto {
  /** */
  isuCd: string;
  /** */
  ppr: number;
  /** */
  mgnRt: number;
  /** */
  stdCcyCd: string;
  /** */
  trdCcyCd: string;
  /** */
  lotMtp: number;
  /** */
  prMtp: number;
  /** */
  potUnt: number;
  /** */
  pipUnt: number;
}

export interface BalanceResponseDto {
  /** */
  trCode: string;
  /** */
  trGb: string;
  /** */
  handle: string;
  /** */
  copCd: string;
  /** */
  empNo: string;
  /** */
  grdGrcd: string;
  /** */
  userIp: string;
  /** */
  dataGrp: string;
  /** */
  user: string;
  /** */
  rcnt?: number;
  /** */
  items?: Array<BalanceResponseItemDto>;
}

export interface BalanceResponseItemDto {
  /** */
  isuCd: string;
  /** */
  trdCcyCd: string;
  /** */
  posDvcd: number;
  /** */
  abkQty: number;
  /** */
  abkPr: number;
  /** */
  ppr: number;
  /** */
  evlPl: number;
  /** */
  pftRt: number;
  /** */
  isuGrcd: string;
}

export interface ResponseDataBalanceResponseDto extends ApiSuccessResponse<BalanceResponseDto> {}

export interface ResponseDataOrderResponseDto extends ApiSuccessResponse<OrderResponseDto> {}
