/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';
import { Email } from './common.types';

export interface MemberApproveRequest {
  /** 회원 유형 */
  memberType: MemberApproveRequestMemberType;
  /** 승인자 */
  approvedAdminUser: string;
}

/**
 * @export
 */
export type MemberApproveRequestMemberType = 'INDIVIDUAL' | 'CORPORATE';

export interface MemberFindIdRequest {
  /** 이름 */
  name: string;
  /** 인증을 완료한 휴대폰 번호 */
  phoneNo: string;
}

export interface MemberFindIdResponse {
  /** 찾은 이메일 */
  email: string;
}

export interface MemberJoinResponse {
  /** */
  id: number;
}

export interface MemberPasswordChangeRequest {
  /** */
  email: Email;
  /** 새로 설정할 비밀번호 */
  newPassword: string;
}

export interface MemberSendSmsCodeRequest {
  /** 이름 */
  name: string;
  /** SMS 인증 코드를 수신할 휴대폰 번호 */
  phoneNo: string;
  /** 인증 용도 */
  useType: MemberSendSmsCodeRequestUseType;
}

/**
 * @export
 */
export type MemberSendSmsCodeRequestUseType = 'SIGN_UP' | 'RESET_PASSWORD' | 'FIND_ID';

export interface MemberVerifySmsCodeRequest {
  /** 이름 */
  name: string;
  /** 인증을 진행할 휴대폰 번호 */
  phoneNo: string;
  /** 6자리 숫자 인증 코드 */
  verificationCode: string;
  /** 인증 용도 */
  useType: MemberVerifySmsCodeRequestUseType;
}

/**
 * @export
 */
export type MemberVerifySmsCodeRequestUseType = 'SIGN_UP' | 'RESET_PASSWORD' | 'FIND_ID';

export interface IndividualMemberJoinRequest {
  /** 투자자를 식별하기 위한 CI (Customer Identification) 값 */
  ci?: string;
  /** */
  email: Email;
  /** 비밀번호 */
  password: string;
  /** 이름 */
  name: string;
  /** 핸드폰 번호 */
  phoneNo: string;
  /** 생년월일 (yyyy-MM-dd 형식) */
  birth: Date;
  /** 성 */
  firstNameEn: string;
  /** 이름 */
  lastNameEn: string;
  /** 주소 */
  address: string;
  /** 주소(영문) */
  addressEn: string;
  /** 상세주소 */
  detailAddress: string;
  /** 상세주소(영문) */
  detailAddressEn: string;
  /** 우편번호 */
  zipCode?: string;
}

export interface CorporateMemberJoinRequest {
  /** 투자자를 식별하기 위한 CI (Customer Identification) 값 */
  ci?: string;
  /** */
  email: Email;
  /** 비밀번호 */
  password: string;
  /** 이름 */
  name: string;
  /** 핸드폰 번호 */
  phoneNo: string;
  /** 법인명 */
  companyName: string;
  /** 법인등록번호 */
  businessNumber: string;
  /** 법인주소 */
  address: string;
  /** 법인주소(영문) */
  addressEn?: string;
  /** 법인상세주소(영문) */
  detailAddressEn?: string;
  /** 법인상세주소 */
  detailAddress: string;
  /** 우편번호 */
  zipCode?: string;
  /** 법인대표 성(영문) */
  representativeEngFirstName: string;
  /** 법인대표 이름(영문) */
  representativeEngLastName: string;
  /** 법인대표 생년월일 (yyyy-MM-dd 형식) */
  representativeBirth: Date;
}

export interface ResponseDataMemberFindIdResponse
  extends ApiSuccessResponse<MemberFindIdResponse> {}

export interface ResponseDataMemberJoinResponse extends ApiSuccessResponse<MemberJoinResponse> {}
