/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface ResponseDataMapTermsNameListResponseTermsByTermsName {
  /** status */
  status: string;
  /** code */
  code: number;
  /** data */
  data?: { [key: string]: Array<ResponseTermsByTermsName> };
}

export interface ResponseDataResponseListResponseTermsByTermsName
  extends ApiSuccessResponse<ResponseListResponseTermsByTermsName> {}

export interface ResponseDataResponseTermsList extends ApiSuccessResponse<ResponseTermsList> {}

export interface ResponseListResponseTermsByTermsName {
  /** */
  contents: Array<ResponseTermsByTermsName>;
}

export interface ResponseTermsByTermsName {
  /** */
  effectiveDate: string;
  /** */
  detail: string;
}

export interface ResponseTermsList {
  /** */
  required: ResponseTermsListRequiredType;
  /** */
  optional: ResponseTermsListOptionalType;
}

/**
 * @export
 */
export type ResponseTermsListRequiredType =
  | 'SERVICE_USAGE_TERMS'
  | 'PERSONAL_INFO_COLLECTION'
  | 'MARKETING_NOTIFICATION';
/**
 * @export
 */
export type ResponseTermsListOptionalType =
  | 'SERVICE_USAGE_TERMS'
  | 'PERSONAL_INFO_COLLECTION'
  | 'MARKETING_NOTIFICATION';
