/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface OrderExecutionHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 주문 시작일자 */
  orderStartDate: Date;
  /** 주문 종료일자 */
  orderEndDate: Date;
  /** 주문구분코드 */
  orderCd: OrderExecutionHistoryRequestOrderCdType;
  /** 포지션구분코드 */
  positionCd: OrderExecutionHistoryRequestPositionCdType;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

/**
 * @export
 */
export type OrderExecutionHistoryRequestOrderCdType = 'TOTAL' | 'BUY_PURCHASE' | 'SELL_PURCHASE';
/**
 * @export
 */
export type OrderExecutionHistoryRequestPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';




export interface OrderExecutionHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 요약 정보 */
  summary: Array<SummaryOrderExecution>;
  /** 상세 정보 */
  details: Array<DetailsOrderExecution>;
}



export interface PaymentHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 청산 시작일자 */
  orderStartDate: Date;
  /** 청산 종료일자 */
  orderEndDate: Date;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}



export interface PaymentHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 상세 정보 */
  details: Array<PaymentDetail>;
}



export interface LiquidationHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 주문 시작일자 */
  orderStartDate: Date;
  /** 주문 종료일자 */
  orderEndDate: Date;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}



export interface LiquidationHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** */
  summary: LiquidationSummary;
  /** 상세 정보 */
  details: Array<LiquidationDetail>;
}



export interface DetailsOrderExecution {
  /** 주문일자 */
  orderDate: Date;
  /** 주문번호 */
  orderNo: string;
  /** 체결일자 */
  executionDate: Date;
  /** 체결번호 */
  executionNo: string;
  /** 종목코드 */
  stockCd: string;
  /** 포지션구분코드 */
  positionCd: string;
  /** 주문유형코드 */
  orderTypeCd: string;
  /** 매매구분코드 */
  sideCd: string;
  /** 주문수량 */
  orderQuantity: number;
  /** 배리어가격 */
  barrierPrice: number;
  /** 주문가격 */
  orderPrice: number;
  /** 이익실현배리어가격 */
  profitRealizationBarrierPrice: number;
  /** 손실제한배리어가격 */
  lossCutBarrierPrice: number;
  /** 체결수량 */
  executionQuantity: number;
  /** 체결가격 */
  executionPrice: number;
  /** 주문잔량 */
  orderBalance: number;
  /** 주문상태코드 */
  orderStatusCd: string;
  /** 접수일시 */
  receptionDate: Date;
  /** 거부사유명 */
  rejectReason: string;
}



export interface SummaryOrderExecution {
  /** 거래통화코드 */
  tradeCurrencyCd: string;
  /** 매수체결수량 */
  longExecutionQuantity: number;
  /** 매수체결금액 */
  longExecutionPrice: number;
  /** 전매체결수량 */
  reShortExecutionQuantity: number;
  /** 전매체결금액 */
  reShortExecutionPrice: number;
  /** 매도체결수량 */
  shortExecutionQuantity: number;
  /** 매도체결금액 */
  shortExecutionPrice: number;
  /** 환매체결수량 */
  reLongExecutionQuantity: number;
  /** 환매체결금액 */
  reLongExecutionPrice: number;
}



export interface PaymentDetail {
  /** 결제일자 */
  paymentDate: Date;
  /** 종목코드 */
  symbolCd: string;
  /** 적요명 */
  description: string;
  /** 거래통화코드 */
  tradeCurrencyCd: string;
  /** 포지션구분코드 */
  positionCd: PaymentDetailPositionCdType;
  /** 거래구분코드 */
  tradeCd: PaymentDetailTradeCdType;
  /** 체결수량 */
  executionQuantity: number;
  /** 체결가격 */
  executionPrice: number;
  /** 체결금액 */
  executionAmount: number;
  /** 결제금액($) */
  paymentAmount: number;
  /** 이전장부수량 */
  beforeBookQuantity: number;
  /** 이후장부수량 */
  afterBookQuantity: number;
  /** 이전예수금($) */
  beforeDeposit: number;
  /** 이후예수금($) */
  afterDeposit: number;
}

/**
 * @export
 */
export type PaymentDetailPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';
/**
 * @export
 */
export type PaymentDetailTradeCdType = 'BUY_PURCHASE' | 'SELL_PURCHASE' | 'DEPOSIT' | 'WITHDRAWAL' | 'DESCRIPTION_DEPOSIT' | 'DESCRIPTION_WITHDRAWAL';




export interface LiquidationDetail {
  /** 청산일자 */
  liquidationDate: Date;
  /** 종목코드 */
  symbolCd: string;
  /** 포지션 구분 */
  orderCd: LiquidationDetailOrderCdType;
  /** 매입가격 */
  purchasePrice: number;
  /** 청산가격 */
  liquidationPrice: number;
  /** 청산수량 */
  liquidationQuantity: number;
  /** 청산손익 */
  liquidationProfitLoss: number;
  /** 스왑수수료 */
  swapCharge: number;
  /** 체결수수료 */
  tradeCharge: number;
  /** 청산순손익 */
  liquidationNetProfitLoss: number;
  /** 매입일시 */
  purchaseDate: Date;
}

/**
 * @export
 */
export type LiquidationDetailOrderCdType = 'TOTAL' | 'BUY_PURCHASE' | 'SELL_PURCHASE';




export interface LiquidationSummary {
  /** LONG 취득금액($) */
  longAcquisitionPrice: number;
  /** LONG 청산금액($) */
  longLiquidationPrice: number;
  /** LONG 청산손익($) */
  longLiquidationProfitLoss: number;
  /** LONG 청산수익율 */
  longLiquidationProfitPercent: number;
  /** LONG 스왑수수료($) */
  longSwapCharge: number;
  /** LONG 체결수수료($) */
  longExecutionCharge: number;
  /** LONG 청산순손익($) */
  longLiquidationNetProfitLoss: number;
  /** LONG 청산순수익율 */
  longLiquidationNetProfitPercent: number;
  /** SHORT 취득금액($) */
  shortAcquisitionPrice: number;
  /** SHORT 청산금액($) */
  shortLiquidationPrice: number;
  /** SHORT 청산손익($) */
  shortLiquidationProfitLoss: number;
  /** SHORT 청산수익율 */
  shortLiquidationProfitPercent: number;
  /** SHORT 스왑수수료($) */
  shortSwapCharge: number;
  /** SHORT 체결수수료($) */
  shortExecutionCharge: number;
  /** SHORT 청산순손익($) */
  shortLiquidationNetProfitLoss: number;
  /** SHORT 청산순수익율 */
  shortLiquidationNetProfitPercent: number;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}



export interface ResponseDataOrderExecutionHistoryResponse extends ApiSuccessResponse<OrderExecutionHistoryResponse> {}



export interface ResponseDataPaymentHistoryResponse extends ApiSuccessResponse<PaymentHistoryResponse> {}



export interface ResponseDataLiquidationHistoryResponse extends ApiSuccessResponse<LiquidationHistoryResponse> {}

