/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';
import { StockCode } from './common.types';

export interface WatchListAddRequest {
  /** */
  stockCode: StockCode;
}



export interface WatchListResponse {
  /** 종목 코드 */
  stockCode: string;
}



export interface PageResponseWatchListResponse {
  /** */
  contents: Array<WatchListResponse>;
  /** 총 페이지 갯수 */
  totalPages?: number;
  /** 총 데이터 건수 */
  totalElements?: number;
  /** 첫번째 페이지 여부 */
  isFirst: boolean;
  /** 마지막 페이지 여부 */
  isLast: boolean;
}



export interface ResponseDataPageResponseWatchListResponse extends ApiSuccessResponse<PageResponseWatchListResponse> {}

