export { default as BaseButton } from './BaseButton/BaseButton.vue';
export { default as BaseTabs } from './BaseTabs/BaseTabs.vue';
export { default as BaseInput } from './BaseInput/BaseInput.vue';
export { default as BaseInputText } from './BaseInput/BaseInputText.vue';
export { default as BaseInputPassword } from './BaseInput/BaseInputPassword.vue';
export { default as BaseProgressBar } from './BaseProgressBar/BaseProgressBar.vue';
export { default as BasePasswordStrength } from './BasePasswordStrength/BasePasswordStrength.vue';
export * from './BasePagination';
export * from './BaseTable';
export * from './BaseIcon';
