export const initialProfitAndLossSummary = {
  longAcquisitionPrice: 0,
  longLiquidationPrice: 0,
  longLiquidationProfitLoss: 0,
  longLiquidationProfitPercent: 0,
  longSwapCharge: 0,
  longExecutionCharge: 0,
  longLiquidationNetProfitLoss: 0,
  longLiquidationNetProfitPercent: 0,
  shortAcquisitionPrice: 0,
  shortLiquidationPrice: 0,
  shortLiquidationProfitLoss: 0,
  shortLiquidationProfitPercent: 0,
  shortSwapCharge: 0,
  shortExecutionCharge: 0,
  shortLiquidationNetProfitLoss: 0,
  shortLiquidationNetProfitPercent: 0,
  nextKey: 0,
};
