/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  color: {
    primary: {
      50: {
        key: "{color.primary.50}",
        value: "#faf5ff",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#faf5ff",
          key: "{color.primary.50}",
        },
        name: "ColorPrimary50",
        attributes: {
          category: "color",
          type: "primary",
          item: "50",
        },
        path: ["color", "primary", "50"],
      },
      100: {
        key: "{color.primary.100}",
        value: "#f3e8ff",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#f3e8ff",
          key: "{color.primary.100}",
        },
        name: "ColorPrimary100",
        attributes: {
          category: "color",
          type: "primary",
          item: "100",
        },
        path: ["color", "primary", "100"],
      },
      200: {
        key: "{color.primary.200}",
        value: "#e9d5ff",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#e9d5ff",
          key: "{color.primary.200}",
        },
        name: "ColorPrimary200",
        attributes: {
          category: "color",
          type: "primary",
          item: "200",
        },
        path: ["color", "primary", "200"],
      },
      300: {
        key: "{color.primary.300}",
        value: "#d8b4fe",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#d8b4fe",
          key: "{color.primary.300}",
        },
        name: "ColorPrimary300",
        attributes: {
          category: "color",
          type: "primary",
          item: "300",
        },
        path: ["color", "primary", "300"],
      },
      400: {
        key: "{color.primary.400}",
        value: "#c084fc",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#c084fc",
          key: "{color.primary.400}",
        },
        name: "ColorPrimary400",
        attributes: {
          category: "color",
          type: "primary",
          item: "400",
        },
        path: ["color", "primary", "400"],
      },
      500: {
        key: "{color.primary.500}",
        value: "#a855f7",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#a855f7",
          key: "{color.primary.500}",
        },
        name: "ColorPrimary500",
        attributes: {
          category: "color",
          type: "primary",
          item: "500",
        },
        path: ["color", "primary", "500"],
      },
      600: {
        key: "{color.primary.600}",
        value: "#9333ea",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#9333ea",
          key: "{color.primary.600}",
        },
        name: "ColorPrimary600",
        attributes: {
          category: "color",
          type: "primary",
          item: "600",
        },
        path: ["color", "primary", "600"],
      },
      700: {
        key: "{color.primary.700}",
        value: "#7c3aed",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#7c3aed",
          key: "{color.primary.700}",
        },
        name: "ColorPrimary700",
        attributes: {
          category: "color",
          type: "primary",
          item: "700",
        },
        path: ["color", "primary", "700"],
      },
      800: {
        key: "{color.primary.800}",
        value: "#6b21a8",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#6b21a8",
          key: "{color.primary.800}",
        },
        name: "ColorPrimary800",
        attributes: {
          category: "color",
          type: "primary",
          item: "800",
        },
        path: ["color", "primary", "800"],
      },
      900: {
        key: "{color.primary.900}",
        value: "#581c87",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#581c87",
          key: "{color.primary.900}",
        },
        name: "ColorPrimary900",
        attributes: {
          category: "color",
          type: "primary",
          item: "900",
        },
        path: ["color", "primary", "900"],
      },
      950: {
        key: "{color.primary.950}",
        value: "#3b0764",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#3b0764",
          key: "{color.primary.950}",
        },
        name: "ColorPrimary950",
        attributes: {
          category: "color",
          type: "primary",
          item: "950",
        },
        path: ["color", "primary", "950"],
      },
    },
    secondary: {
      50: {
        key: "{color.secondary.50}",
        value: "#f8fafc",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#f8fafc",
          key: "{color.secondary.50}",
        },
        name: "ColorSecondary50",
        attributes: {
          category: "color",
          type: "secondary",
          item: "50",
        },
        path: ["color", "secondary", "50"],
      },
      100: {
        key: "{color.secondary.100}",
        value: "#f1f5f9",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#f1f5f9",
          key: "{color.secondary.100}",
        },
        name: "ColorSecondary100",
        attributes: {
          category: "color",
          type: "secondary",
          item: "100",
        },
        path: ["color", "secondary", "100"],
      },
      200: {
        key: "{color.secondary.200}",
        value: "#e2e8f0",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#e2e8f0",
          key: "{color.secondary.200}",
        },
        name: "ColorSecondary200",
        attributes: {
          category: "color",
          type: "secondary",
          item: "200",
        },
        path: ["color", "secondary", "200"],
      },
      300: {
        key: "{color.secondary.300}",
        value: "#cbd5e1",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#cbd5e1",
          key: "{color.secondary.300}",
        },
        name: "ColorSecondary300",
        attributes: {
          category: "color",
          type: "secondary",
          item: "300",
        },
        path: ["color", "secondary", "300"],
      },
      400: {
        key: "{color.secondary.400}",
        value: "#94a3b8",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#94a3b8",
          key: "{color.secondary.400}",
        },
        name: "ColorSecondary400",
        attributes: {
          category: "color",
          type: "secondary",
          item: "400",
        },
        path: ["color", "secondary", "400"],
      },
      500: {
        key: "{color.secondary.500}",
        value: "#64748b",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#64748b",
          key: "{color.secondary.500}",
        },
        name: "ColorSecondary500",
        attributes: {
          category: "color",
          type: "secondary",
          item: "500",
        },
        path: ["color", "secondary", "500"],
      },
      600: {
        key: "{color.secondary.600}",
        value: "#475569",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#475569",
          key: "{color.secondary.600}",
        },
        name: "ColorSecondary600",
        attributes: {
          category: "color",
          type: "secondary",
          item: "600",
        },
        path: ["color", "secondary", "600"],
      },
      700: {
        key: "{color.secondary.700}",
        value: "#334155",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#334155",
          key: "{color.secondary.700}",
        },
        name: "ColorSecondary700",
        attributes: {
          category: "color",
          type: "secondary",
          item: "700",
        },
        path: ["color", "secondary", "700"],
      },
      800: {
        key: "{color.secondary.800}",
        value: "#1e293b",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#1e293b",
          key: "{color.secondary.800}",
        },
        name: "ColorSecondary800",
        attributes: {
          category: "color",
          type: "secondary",
          item: "800",
        },
        path: ["color", "secondary", "800"],
      },
      900: {
        key: "{color.secondary.900}",
        value: "#0f172a",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#0f172a",
          key: "{color.secondary.900}",
        },
        name: "ColorSecondary900",
        attributes: {
          category: "color",
          type: "secondary",
          item: "900",
        },
        path: ["color", "secondary", "900"],
      },
      950: {
        key: "{color.secondary.950}",
        value: "#020617",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#020617",
          key: "{color.secondary.950}",
        },
        name: "ColorSecondary950",
        attributes: {
          category: "color",
          type: "secondary",
          item: "950",
        },
        path: ["color", "secondary", "950"],
      },
    },
    success: {
      50: {
        key: "{color.success.50}",
        value: "#f0fdf4",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#f0fdf4",
          key: "{color.success.50}",
        },
        name: "ColorSuccess50",
        attributes: {
          category: "color",
          type: "success",
          item: "50",
        },
        path: ["color", "success", "50"],
      },
      100: {
        key: "{color.success.100}",
        value: "#dcfce7",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#dcfce7",
          key: "{color.success.100}",
        },
        name: "ColorSuccess100",
        attributes: {
          category: "color",
          type: "success",
          item: "100",
        },
        path: ["color", "success", "100"],
      },
      200: {
        key: "{color.success.200}",
        value: "#bbf7d0",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#bbf7d0",
          key: "{color.success.200}",
        },
        name: "ColorSuccess200",
        attributes: {
          category: "color",
          type: "success",
          item: "200",
        },
        path: ["color", "success", "200"],
      },
      300: {
        key: "{color.success.300}",
        value: "#86efac",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#86efac",
          key: "{color.success.300}",
        },
        name: "ColorSuccess300",
        attributes: {
          category: "color",
          type: "success",
          item: "300",
        },
        path: ["color", "success", "300"],
      },
      400: {
        key: "{color.success.400}",
        value: "#4ade80",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#4ade80",
          key: "{color.success.400}",
        },
        name: "ColorSuccess400",
        attributes: {
          category: "color",
          type: "success",
          item: "400",
        },
        path: ["color", "success", "400"],
      },
      500: {
        key: "{color.success.500}",
        value: "#22c55e",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#22c55e",
          key: "{color.success.500}",
        },
        name: "ColorSuccess500",
        attributes: {
          category: "color",
          type: "success",
          item: "500",
        },
        path: ["color", "success", "500"],
      },
      600: {
        key: "{color.success.600}",
        value: "#16a34a",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#16a34a",
          key: "{color.success.600}",
        },
        name: "ColorSuccess600",
        attributes: {
          category: "color",
          type: "success",
          item: "600",
        },
        path: ["color", "success", "600"],
      },
      700: {
        key: "{color.success.700}",
        value: "#15803d",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#15803d",
          key: "{color.success.700}",
        },
        name: "ColorSuccess700",
        attributes: {
          category: "color",
          type: "success",
          item: "700",
        },
        path: ["color", "success", "700"],
      },
      800: {
        key: "{color.success.800}",
        value: "#166534",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#166534",
          key: "{color.success.800}",
        },
        name: "ColorSuccess800",
        attributes: {
          category: "color",
          type: "success",
          item: "800",
        },
        path: ["color", "success", "800"],
      },
      900: {
        key: "{color.success.900}",
        value: "#14532d",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#14532d",
          key: "{color.success.900}",
        },
        name: "ColorSuccess900",
        attributes: {
          category: "color",
          type: "success",
          item: "900",
        },
        path: ["color", "success", "900"],
      },
      950: {
        key: "{color.success.950}",
        value: "#052e16",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#052e16",
          key: "{color.success.950}",
        },
        name: "ColorSuccess950",
        attributes: {
          category: "color",
          type: "success",
          item: "950",
        },
        path: ["color", "success", "950"],
      },
    },
    warning: {
      50: {
        key: "{color.warning.50}",
        value: "#fffbeb",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fffbeb",
          key: "{color.warning.50}",
        },
        name: "ColorWarning50",
        attributes: {
          category: "color",
          type: "warning",
          item: "50",
        },
        path: ["color", "warning", "50"],
      },
      100: {
        key: "{color.warning.100}",
        value: "#fef3c7",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fef3c7",
          key: "{color.warning.100}",
        },
        name: "ColorWarning100",
        attributes: {
          category: "color",
          type: "warning",
          item: "100",
        },
        path: ["color", "warning", "100"],
      },
      200: {
        key: "{color.warning.200}",
        value: "#fde68a",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fde68a",
          key: "{color.warning.200}",
        },
        name: "ColorWarning200",
        attributes: {
          category: "color",
          type: "warning",
          item: "200",
        },
        path: ["color", "warning", "200"],
      },
      300: {
        key: "{color.warning.300}",
        value: "#fcd34d",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fcd34d",
          key: "{color.warning.300}",
        },
        name: "ColorWarning300",
        attributes: {
          category: "color",
          type: "warning",
          item: "300",
        },
        path: ["color", "warning", "300"],
      },
      400: {
        key: "{color.warning.400}",
        value: "#fbbf24",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fbbf24",
          key: "{color.warning.400}",
        },
        name: "ColorWarning400",
        attributes: {
          category: "color",
          type: "warning",
          item: "400",
        },
        path: ["color", "warning", "400"],
      },
      500: {
        key: "{color.warning.500}",
        value: "#f59e0b",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#f59e0b",
          key: "{color.warning.500}",
        },
        name: "ColorWarning500",
        attributes: {
          category: "color",
          type: "warning",
          item: "500",
        },
        path: ["color", "warning", "500"],
      },
      600: {
        key: "{color.warning.600}",
        value: "#d97706",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#d97706",
          key: "{color.warning.600}",
        },
        name: "ColorWarning600",
        attributes: {
          category: "color",
          type: "warning",
          item: "600",
        },
        path: ["color", "warning", "600"],
      },
      700: {
        key: "{color.warning.700}",
        value: "#b45309",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#b45309",
          key: "{color.warning.700}",
        },
        name: "ColorWarning700",
        attributes: {
          category: "color",
          type: "warning",
          item: "700",
        },
        path: ["color", "warning", "700"],
      },
      800: {
        key: "{color.warning.800}",
        value: "#92400e",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#92400e",
          key: "{color.warning.800}",
        },
        name: "ColorWarning800",
        attributes: {
          category: "color",
          type: "warning",
          item: "800",
        },
        path: ["color", "warning", "800"],
      },
      900: {
        key: "{color.warning.900}",
        value: "#78350f",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#78350f",
          key: "{color.warning.900}",
        },
        name: "ColorWarning900",
        attributes: {
          category: "color",
          type: "warning",
          item: "900",
        },
        path: ["color", "warning", "900"],
      },
      950: {
        key: "{color.warning.950}",
        value: "#451a03",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#451a03",
          key: "{color.warning.950}",
        },
        name: "ColorWarning950",
        attributes: {
          category: "color",
          type: "warning",
          item: "950",
        },
        path: ["color", "warning", "950"],
      },
    },
    error: {
      50: {
        key: "{color.error.50}",
        value: "#fef2f2",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fef2f2",
          key: "{color.error.50}",
        },
        name: "ColorError50",
        attributes: {
          category: "color",
          type: "error",
          item: "50",
        },
        path: ["color", "error", "50"],
      },
      100: {
        key: "{color.error.100}",
        value: "#fee2e2",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fee2e2",
          key: "{color.error.100}",
        },
        name: "ColorError100",
        attributes: {
          category: "color",
          type: "error",
          item: "100",
        },
        path: ["color", "error", "100"],
      },
      200: {
        key: "{color.error.200}",
        value: "#fecaca",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fecaca",
          key: "{color.error.200}",
        },
        name: "ColorError200",
        attributes: {
          category: "color",
          type: "error",
          item: "200",
        },
        path: ["color", "error", "200"],
      },
      300: {
        key: "{color.error.300}",
        value: "#fca5a5",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#fca5a5",
          key: "{color.error.300}",
        },
        name: "ColorError300",
        attributes: {
          category: "color",
          type: "error",
          item: "300",
        },
        path: ["color", "error", "300"],
      },
      400: {
        key: "{color.error.400}",
        value: "#f87171",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#f87171",
          key: "{color.error.400}",
        },
        name: "ColorError400",
        attributes: {
          category: "color",
          type: "error",
          item: "400",
        },
        path: ["color", "error", "400"],
      },
      500: {
        key: "{color.error.500}",
        value: "#ef4444",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#ef4444",
          key: "{color.error.500}",
        },
        name: "ColorError500",
        attributes: {
          category: "color",
          type: "error",
          item: "500",
        },
        path: ["color", "error", "500"],
      },
      600: {
        key: "{color.error.600}",
        value: "#dc2626",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#dc2626",
          key: "{color.error.600}",
        },
        name: "ColorError600",
        attributes: {
          category: "color",
          type: "error",
          item: "600",
        },
        path: ["color", "error", "600"],
      },
      700: {
        key: "{color.error.700}",
        value: "#b91c1c",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#b91c1c",
          key: "{color.error.700}",
        },
        name: "ColorError700",
        attributes: {
          category: "color",
          type: "error",
          item: "700",
        },
        path: ["color", "error", "700"],
      },
      800: {
        key: "{color.error.800}",
        value: "#991b1b",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#991b1b",
          key: "{color.error.800}",
        },
        name: "ColorError800",
        attributes: {
          category: "color",
          type: "error",
          item: "800",
        },
        path: ["color", "error", "800"],
      },
      900: {
        key: "{color.error.900}",
        value: "#7f1d1d",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#7f1d1d",
          key: "{color.error.900}",
        },
        name: "ColorError900",
        attributes: {
          category: "color",
          type: "error",
          item: "900",
        },
        path: ["color", "error", "900"],
      },
      950: {
        key: "{color.error.950}",
        value: "#450a0a",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#450a0a",
          key: "{color.error.950}",
        },
        name: "ColorError950",
        attributes: {
          category: "color",
          type: "error",
          item: "950",
        },
        path: ["color", "error", "950"],
      },
    },
    neutral: {
      white: {
        key: "{color.neutral.white}",
        value: "#ffffff",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#ffffff",
          key: "{color.neutral.white}",
        },
        name: "ColorNeutralWhite",
        attributes: {
          category: "color",
          type: "neutral",
          item: "white",
        },
        path: ["color", "neutral", "white"],
      },
      black: {
        key: "{color.neutral.black}",
        value: "#000000",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#000000",
          key: "{color.neutral.black}",
        },
        name: "ColorNeutralBlack",
        attributes: {
          category: "color",
          type: "neutral",
          item: "black",
        },
        path: ["color", "neutral", "black"],
      },
      transparent: {
        key: "{color.neutral.transparent}",
        value: "transparent",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "transparent",
          key: "{color.neutral.transparent}",
        },
        name: "ColorNeutralTransparent",
        attributes: {
          category: "color",
          type: "neutral",
          item: "transparent",
        },
        path: ["color", "neutral", "transparent"],
      },
    },
  },
  shadow: {
    sm: {
      key: "{shadow.sm}",
      value: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        key: "{shadow.sm}",
      },
      name: "ShadowSm",
      attributes: {
        category: "shadow",
        type: "sm",
      },
      path: ["shadow", "sm"],
    },
    base: {
      key: "{shadow.base}",
      value: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        key: "{shadow.base}",
      },
      name: "ShadowBase",
      attributes: {
        category: "shadow",
        type: "base",
      },
      path: ["shadow", "base"],
    },
    md: {
      key: "{shadow.md}",
      value: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value:
          "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        key: "{shadow.md}",
      },
      name: "ShadowMd",
      attributes: {
        category: "shadow",
        type: "md",
      },
      path: ["shadow", "md"],
    },
    lg: {
      key: "{shadow.lg}",
      value:
        "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value:
          "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        key: "{shadow.lg}",
      },
      name: "ShadowLg",
      attributes: {
        category: "shadow",
        type: "lg",
      },
      path: ["shadow", "lg"],
    },
    xl: {
      key: "{shadow.xl}",
      value:
        "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value:
          "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
        key: "{shadow.xl}",
      },
      name: "ShadowXl",
      attributes: {
        category: "shadow",
        type: "xl",
      },
      path: ["shadow", "xl"],
    },
    "2xl": {
      key: "{shadow.2xl}",
      value: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
        key: "{shadow.2xl}",
      },
      name: "Shadow2xl",
      attributes: {
        category: "shadow",
        type: "2xl",
      },
      path: ["shadow", "2xl"],
    },
    inner: {
      key: "{shadow.inner}",
      value: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
        key: "{shadow.inner}",
      },
      name: "ShadowInner",
      attributes: {
        category: "shadow",
        type: "inner",
      },
      path: ["shadow", "inner"],
    },
    none: {
      key: "{shadow.none}",
      value: "none",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "none",
        key: "{shadow.none}",
      },
      name: "ShadowNone",
      attributes: {
        category: "shadow",
        type: "none",
      },
      path: ["shadow", "none"],
    },
  },
  spacing: {
    0: {
      5: {
        key: "{spacing.0.5}",
        value: "0.125rem",
        filePath: "src/tokens/spacing.json",
        isSource: true,
        original: {
          value: "0.125rem",
          key: "{spacing.0.5}",
        },
        name: "Spacing05",
        attributes: {
          category: "spacing",
          type: "0",
          item: "5",
        },
        path: ["spacing", "0", "5"],
      },
      key: "{spacing.0}",
      value: "0",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "0",
        key: "{spacing.0}",
      },
      name: "Spacing0",
      attributes: {
        category: "spacing",
        type: "0",
      },
      path: ["spacing", "0"],
    },
    1: {
      5: {
        key: "{spacing.1.5}",
        value: "0.375rem",
        filePath: "src/tokens/spacing.json",
        isSource: true,
        original: {
          value: "0.375rem",
          key: "{spacing.1.5}",
        },
        name: "Spacing15",
        attributes: {
          category: "spacing",
          type: "1",
          item: "5",
        },
        path: ["spacing", "1", "5"],
      },
      key: "{spacing.1}",
      value: "0.25rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "0.25rem",
        key: "{spacing.1}",
      },
      name: "Spacing1",
      attributes: {
        category: "spacing",
        type: "1",
      },
      path: ["spacing", "1"],
    },
    2: {
      5: {
        key: "{spacing.2.5}",
        value: "0.625rem",
        filePath: "src/tokens/spacing.json",
        isSource: true,
        original: {
          value: "0.625rem",
          key: "{spacing.2.5}",
        },
        name: "Spacing25",
        attributes: {
          category: "spacing",
          type: "2",
          item: "5",
        },
        path: ["spacing", "2", "5"],
      },
      key: "{spacing.2}",
      value: "0.5rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "0.5rem",
        key: "{spacing.2}",
      },
      name: "Spacing2",
      attributes: {
        category: "spacing",
        type: "2",
      },
      path: ["spacing", "2"],
    },
    3: {
      5: {
        key: "{spacing.3.5}",
        value: "0.875rem",
        filePath: "src/tokens/spacing.json",
        isSource: true,
        original: {
          value: "0.875rem",
          key: "{spacing.3.5}",
        },
        name: "Spacing35",
        attributes: {
          category: "spacing",
          type: "3",
          item: "5",
        },
        path: ["spacing", "3", "5"],
      },
      key: "{spacing.3}",
      value: "0.75rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "0.75rem",
        key: "{spacing.3}",
      },
      name: "Spacing3",
      attributes: {
        category: "spacing",
        type: "3",
      },
      path: ["spacing", "3"],
    },
    4: {
      key: "{spacing.4}",
      value: "1rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "1rem",
        key: "{spacing.4}",
      },
      name: "Spacing4",
      attributes: {
        category: "spacing",
        type: "4",
      },
      path: ["spacing", "4"],
    },
    5: {
      key: "{spacing.5}",
      value: "1.25rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "1.25rem",
        key: "{spacing.5}",
      },
      name: "Spacing5",
      attributes: {
        category: "spacing",
        type: "5",
      },
      path: ["spacing", "5"],
    },
    6: {
      key: "{spacing.6}",
      value: "1.5rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "1.5rem",
        key: "{spacing.6}",
      },
      name: "Spacing6",
      attributes: {
        category: "spacing",
        type: "6",
      },
      path: ["spacing", "6"],
    },
    7: {
      key: "{spacing.7}",
      value: "1.75rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "1.75rem",
        key: "{spacing.7}",
      },
      name: "Spacing7",
      attributes: {
        category: "spacing",
        type: "7",
      },
      path: ["spacing", "7"],
    },
    8: {
      key: "{spacing.8}",
      value: "2rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "2rem",
        key: "{spacing.8}",
      },
      name: "Spacing8",
      attributes: {
        category: "spacing",
        type: "8",
      },
      path: ["spacing", "8"],
    },
    9: {
      key: "{spacing.9}",
      value: "2.25rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "2.25rem",
        key: "{spacing.9}",
      },
      name: "Spacing9",
      attributes: {
        category: "spacing",
        type: "9",
      },
      path: ["spacing", "9"],
    },
    10: {
      key: "{spacing.10}",
      value: "2.5rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "2.5rem",
        key: "{spacing.10}",
      },
      name: "Spacing10",
      attributes: {
        category: "spacing",
        type: "10",
      },
      path: ["spacing", "10"],
    },
    11: {
      key: "{spacing.11}",
      value: "2.75rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "2.75rem",
        key: "{spacing.11}",
      },
      name: "Spacing11",
      attributes: {
        category: "spacing",
        type: "11",
      },
      path: ["spacing", "11"],
    },
    12: {
      key: "{spacing.12}",
      value: "3rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "3rem",
        key: "{spacing.12}",
      },
      name: "Spacing12",
      attributes: {
        category: "spacing",
        type: "12",
      },
      path: ["spacing", "12"],
    },
    14: {
      key: "{spacing.14}",
      value: "3.5rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "3.5rem",
        key: "{spacing.14}",
      },
      name: "Spacing14",
      attributes: {
        category: "spacing",
        type: "14",
      },
      path: ["spacing", "14"],
    },
    16: {
      key: "{spacing.16}",
      value: "4rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "4rem",
        key: "{spacing.16}",
      },
      name: "Spacing16",
      attributes: {
        category: "spacing",
        type: "16",
      },
      path: ["spacing", "16"],
    },
    20: {
      key: "{spacing.20}",
      value: "5rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "5rem",
        key: "{spacing.20}",
      },
      name: "Spacing20",
      attributes: {
        category: "spacing",
        type: "20",
      },
      path: ["spacing", "20"],
    },
    24: {
      key: "{spacing.24}",
      value: "6rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "6rem",
        key: "{spacing.24}",
      },
      name: "Spacing24",
      attributes: {
        category: "spacing",
        type: "24",
      },
      path: ["spacing", "24"],
    },
    28: {
      key: "{spacing.28}",
      value: "7rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "7rem",
        key: "{spacing.28}",
      },
      name: "Spacing28",
      attributes: {
        category: "spacing",
        type: "28",
      },
      path: ["spacing", "28"],
    },
    32: {
      key: "{spacing.32}",
      value: "8rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "8rem",
        key: "{spacing.32}",
      },
      name: "Spacing32",
      attributes: {
        category: "spacing",
        type: "32",
      },
      path: ["spacing", "32"],
    },
    36: {
      key: "{spacing.36}",
      value: "9rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "9rem",
        key: "{spacing.36}",
      },
      name: "Spacing36",
      attributes: {
        category: "spacing",
        type: "36",
      },
      path: ["spacing", "36"],
    },
    40: {
      key: "{spacing.40}",
      value: "10rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "10rem",
        key: "{spacing.40}",
      },
      name: "Spacing40",
      attributes: {
        category: "spacing",
        type: "40",
      },
      path: ["spacing", "40"],
    },
    44: {
      key: "{spacing.44}",
      value: "11rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "11rem",
        key: "{spacing.44}",
      },
      name: "Spacing44",
      attributes: {
        category: "spacing",
        type: "44",
      },
      path: ["spacing", "44"],
    },
    48: {
      key: "{spacing.48}",
      value: "12rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "12rem",
        key: "{spacing.48}",
      },
      name: "Spacing48",
      attributes: {
        category: "spacing",
        type: "48",
      },
      path: ["spacing", "48"],
    },
    52: {
      key: "{spacing.52}",
      value: "13rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "13rem",
        key: "{spacing.52}",
      },
      name: "Spacing52",
      attributes: {
        category: "spacing",
        type: "52",
      },
      path: ["spacing", "52"],
    },
    56: {
      key: "{spacing.56}",
      value: "14rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "14rem",
        key: "{spacing.56}",
      },
      name: "Spacing56",
      attributes: {
        category: "spacing",
        type: "56",
      },
      path: ["spacing", "56"],
    },
    60: {
      key: "{spacing.60}",
      value: "15rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "15rem",
        key: "{spacing.60}",
      },
      name: "Spacing60",
      attributes: {
        category: "spacing",
        type: "60",
      },
      path: ["spacing", "60"],
    },
    64: {
      key: "{spacing.64}",
      value: "16rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "16rem",
        key: "{spacing.64}",
      },
      name: "Spacing64",
      attributes: {
        category: "spacing",
        type: "64",
      },
      path: ["spacing", "64"],
    },
    72: {
      key: "{spacing.72}",
      value: "18rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "18rem",
        key: "{spacing.72}",
      },
      name: "Spacing72",
      attributes: {
        category: "spacing",
        type: "72",
      },
      path: ["spacing", "72"],
    },
    80: {
      key: "{spacing.80}",
      value: "20rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "20rem",
        key: "{spacing.80}",
      },
      name: "Spacing80",
      attributes: {
        category: "spacing",
        type: "80",
      },
      path: ["spacing", "80"],
    },
    96: {
      key: "{spacing.96}",
      value: "24rem",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "24rem",
        key: "{spacing.96}",
      },
      name: "Spacing96",
      attributes: {
        category: "spacing",
        type: "96",
      },
      path: ["spacing", "96"],
    },
    px: {
      key: "{spacing.px}",
      value: "1px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "1px",
        key: "{spacing.px}",
      },
      name: "SpacingPx",
      attributes: {
        category: "spacing",
        type: "px",
      },
      path: ["spacing", "px"],
    },
  },
  typography: {
    fontFamily: {
      sans: {
        key: "{typography.fontFamily.sans}",
        value: "Inter, system-ui, -apple-system, sans-serif",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "Inter, system-ui, -apple-system, sans-serif",
          key: "{typography.fontFamily.sans}",
        },
        name: "TypographyFontFamilySans",
        attributes: {
          category: "typography",
          type: "fontFamily",
          item: "sans",
        },
        path: ["typography", "fontFamily", "sans"],
      },
      serif: {
        key: "{typography.fontFamily.serif}",
        value: "Georgia, serif",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "Georgia, serif",
          key: "{typography.fontFamily.serif}",
        },
        name: "TypographyFontFamilySerif",
        attributes: {
          category: "typography",
          type: "fontFamily",
          item: "serif",
        },
        path: ["typography", "fontFamily", "serif"],
      },
      mono: {
        key: "{typography.fontFamily.mono}",
        value: "JetBrains Mono, monospace",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "JetBrains Mono, monospace",
          key: "{typography.fontFamily.mono}",
        },
        name: "TypographyFontFamilyMono",
        attributes: {
          category: "typography",
          type: "fontFamily",
          item: "mono",
        },
        path: ["typography", "fontFamily", "mono"],
      },
    },
    fontSize: {
      xs: {
        key: "{typography.fontSize.xs}",
        value: "0.75rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "0.75rem",
          key: "{typography.fontSize.xs}",
        },
        name: "TypographyFontSizeXs",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "xs",
        },
        path: ["typography", "fontSize", "xs"],
      },
      sm: {
        key: "{typography.fontSize.sm}",
        value: "0.875rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "0.875rem",
          key: "{typography.fontSize.sm}",
        },
        name: "TypographyFontSizeSm",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "sm",
        },
        path: ["typography", "fontSize", "sm"],
      },
      base: {
        key: "{typography.fontSize.base}",
        value: "1rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1rem",
          key: "{typography.fontSize.base}",
        },
        name: "TypographyFontSizeBase",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "base",
        },
        path: ["typography", "fontSize", "base"],
      },
      lg: {
        key: "{typography.fontSize.lg}",
        value: "1.125rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.125rem",
          key: "{typography.fontSize.lg}",
        },
        name: "TypographyFontSizeLg",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "lg",
        },
        path: ["typography", "fontSize", "lg"],
      },
      xl: {
        key: "{typography.fontSize.xl}",
        value: "1.25rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.25rem",
          key: "{typography.fontSize.xl}",
        },
        name: "TypographyFontSizeXl",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "xl",
        },
        path: ["typography", "fontSize", "xl"],
      },
      "2xl": {
        key: "{typography.fontSize.2xl}",
        value: "1.5rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.5rem",
          key: "{typography.fontSize.2xl}",
        },
        name: "TypographyFontSize2xl",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "2xl",
        },
        path: ["typography", "fontSize", "2xl"],
      },
      "3xl": {
        key: "{typography.fontSize.3xl}",
        value: "1.875rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.875rem",
          key: "{typography.fontSize.3xl}",
        },
        name: "TypographyFontSize3xl",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "3xl",
        },
        path: ["typography", "fontSize", "3xl"],
      },
      "4xl": {
        key: "{typography.fontSize.4xl}",
        value: "2.25rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "2.25rem",
          key: "{typography.fontSize.4xl}",
        },
        name: "TypographyFontSize4xl",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "4xl",
        },
        path: ["typography", "fontSize", "4xl"],
      },
      "5xl": {
        key: "{typography.fontSize.5xl}",
        value: "3rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "3rem",
          key: "{typography.fontSize.5xl}",
        },
        name: "TypographyFontSize5xl",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "5xl",
        },
        path: ["typography", "fontSize", "5xl"],
      },
      "6xl": {
        key: "{typography.fontSize.6xl}",
        value: "3.75rem",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "3.75rem",
          key: "{typography.fontSize.6xl}",
        },
        name: "TypographyFontSize6xl",
        attributes: {
          category: "typography",
          type: "fontSize",
          item: "6xl",
        },
        path: ["typography", "fontSize", "6xl"],
      },
    },
    fontWeight: {
      thin: {
        key: "{typography.fontWeight.thin}",
        value: "100",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "100",
          key: "{typography.fontWeight.thin}",
        },
        name: "TypographyFontWeightThin",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "thin",
        },
        path: ["typography", "fontWeight", "thin"],
      },
      light: {
        key: "{typography.fontWeight.light}",
        value: "300",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "300",
          key: "{typography.fontWeight.light}",
        },
        name: "TypographyFontWeightLight",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "light",
        },
        path: ["typography", "fontWeight", "light"],
      },
      normal: {
        key: "{typography.fontWeight.normal}",
        value: "400",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "400",
          key: "{typography.fontWeight.normal}",
        },
        name: "TypographyFontWeightNormal",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "normal",
        },
        path: ["typography", "fontWeight", "normal"],
      },
      medium: {
        key: "{typography.fontWeight.medium}",
        value: "500",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "500",
          key: "{typography.fontWeight.medium}",
        },
        name: "TypographyFontWeightMedium",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "medium",
        },
        path: ["typography", "fontWeight", "medium"],
      },
      semibold: {
        key: "{typography.fontWeight.semibold}",
        value: "600",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "600",
          key: "{typography.fontWeight.semibold}",
        },
        name: "TypographyFontWeightSemibold",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "semibold",
        },
        path: ["typography", "fontWeight", "semibold"],
      },
      bold: {
        key: "{typography.fontWeight.bold}",
        value: "700",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "700",
          key: "{typography.fontWeight.bold}",
        },
        name: "TypographyFontWeightBold",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "bold",
        },
        path: ["typography", "fontWeight", "bold"],
      },
      extrabold: {
        key: "{typography.fontWeight.extrabold}",
        value: "800",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "800",
          key: "{typography.fontWeight.extrabold}",
        },
        name: "TypographyFontWeightExtrabold",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "extrabold",
        },
        path: ["typography", "fontWeight", "extrabold"],
      },
      black: {
        key: "{typography.fontWeight.black}",
        value: "900",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "900",
          key: "{typography.fontWeight.black}",
        },
        name: "TypographyFontWeightBlack",
        attributes: {
          category: "typography",
          type: "fontWeight",
          item: "black",
        },
        path: ["typography", "fontWeight", "black"],
      },
    },
    lineHeight: {
      none: {
        key: "{typography.lineHeight.none}",
        value: "1",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1",
          key: "{typography.lineHeight.none}",
        },
        name: "TypographyLineHeightNone",
        attributes: {
          category: "typography",
          type: "lineHeight",
          item: "none",
        },
        path: ["typography", "lineHeight", "none"],
      },
      tight: {
        key: "{typography.lineHeight.tight}",
        value: "1.25",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.25",
          key: "{typography.lineHeight.tight}",
        },
        name: "TypographyLineHeightTight",
        attributes: {
          category: "typography",
          type: "lineHeight",
          item: "tight",
        },
        path: ["typography", "lineHeight", "tight"],
      },
      snug: {
        key: "{typography.lineHeight.snug}",
        value: "1.375",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.375",
          key: "{typography.lineHeight.snug}",
        },
        name: "TypographyLineHeightSnug",
        attributes: {
          category: "typography",
          type: "lineHeight",
          item: "snug",
        },
        path: ["typography", "lineHeight", "snug"],
      },
      normal: {
        key: "{typography.lineHeight.normal}",
        value: "1.5",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.5",
          key: "{typography.lineHeight.normal}",
        },
        name: "TypographyLineHeightNormal",
        attributes: {
          category: "typography",
          type: "lineHeight",
          item: "normal",
        },
        path: ["typography", "lineHeight", "normal"],
      },
      relaxed: {
        key: "{typography.lineHeight.relaxed}",
        value: "1.625",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "1.625",
          key: "{typography.lineHeight.relaxed}",
        },
        name: "TypographyLineHeightRelaxed",
        attributes: {
          category: "typography",
          type: "lineHeight",
          item: "relaxed",
        },
        path: ["typography", "lineHeight", "relaxed"],
      },
      loose: {
        key: "{typography.lineHeight.loose}",
        value: "2",
        filePath: "src/tokens/typography.json",
        isSource: true,
        original: {
          value: "2",
          key: "{typography.lineHeight.loose}",
        },
        name: "TypographyLineHeightLoose",
        attributes: {
          category: "typography",
          type: "lineHeight",
          item: "loose",
        },
        path: ["typography", "lineHeight", "loose"],
      },
    },
  },
};
