/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: ['./src/**/*.{ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      baseColors: {
        primary: {
          primary800: 'var(--base-colors-primary-primary800)',
          primary700: 'var(--base-colors-primary-primary700)',
          primary600: 'var(--base-colors-primary-primary600)',
          primary500: 'var(--base-colors-primary-primary500)',
          primary400: 'var(--base-colors-primary-primary400)',
          primary300: 'var(--base-colors-primary-primary300)',
          primary200: 'var(--base-colors-primary-primary200)',
          primary100: 'var(--base-colors-primary-primary100)',
          primary050: 'var(--base-colors-primary-primary050)',
          primaryDeep: 'var(--base-colors-primary-primary-deep)',
        },
        neutral: {
          neutral800: 'var(--base-colors-neutral-neutral800)',
          neutral700: 'var(--base-colors-neutral-neutral700)',
          neutral600: 'var(--base-colors-neutral-neutral600)',
          neutral500: 'var(--base-colors-neutral-neutral500)',
          neutral400: 'var(--base-colors-neutral-neutral400)',
          neutral300: 'var(--base-colors-neutral-neutral300)',
          neutral200: 'var(--base-colors-neutral-neutral200)',
          neutral100: 'var(--base-colors-neutral-neutral100)',
          neutral000: 'var(--base-colors-neutral-neutral000)',
          neutral750: 'var(--base-colors-neutral-neutral750)',
          neutral250: 'var(--base-colors-neutral-neutral250)',
          neutral150: 'var(--base-colors-neutral-neutral150)',
          neutral550: 'var(--base-colors-neutral-neutral550)',
          neutral050: 'var(--base-colors-neutral-neutral050)',
        },
        green: {
          green100: 'var(--base-colors-green-green100)',
          green200: 'var(--base-colors-green-green200)',
          green300: 'var(--base-colors-green-green300)',
          green400: 'var(--base-colors-green-green400)',
          green600: 'var(--base-colors-green-green600)',
          green700: 'var(--base-colors-green-green700)',
          green500: 'var(--base-colors-green-green500)',
          green800: 'var(--base-colors-green-green800)',
          green050: 'var(--base-colors-green-green050)',
        },
        red: {
          red800: 'var(--base-colors-red-red800)',
          red700: 'var(--base-colors-red-red700)',
          red600: 'var(--base-colors-red-red600)',
          red500: 'var(--base-colors-red-red500)',
          red400: 'var(--base-colors-red-red400)',
          red300: 'var(--base-colors-red-red300)',
          red200: 'var(--base-colors-red-red200)',
          red100: 'var(--base-colors-red-red100)',
          red050: 'var(--base-colors-red-red050)',
        },
        blue: {
          blue800Deep: 'var(--base-colors-blue-blue800-deep)',
          blue700: 'var(--base-colors-blue-blue700)',
          blue600: 'var(--base-colors-blue-blue600)',
          blue500: 'var(--base-colors-blue-blue500)',
          blue400: 'var(--base-colors-blue-blue400)',
          blue300: 'var(--base-colors-blue-blue300)',
          blue200: 'var(--base-colors-blue-blue200)',
          blue100: 'var(--base-colors-blue-blue100)',
          blue050: 'var(--base-colors-blue-blue050)',
          blue800: 'var(--base-colors-blue-blue800)',
        },
        common: {
          bgSurfaceDefault: 'var(--base-colors-common-bg-surface-default)',
          lightGrayCa: 'var(--base-colors-common-light-gray-ca)',
          lightGrayF5: 'var(--base-colors-common-light-gray-f5)',
          lightGrayEa: 'var(--base-colors-common-light-gray-ea)',
        },
        purple: {
          purple800: 'var(--base-colors-purple-purple800)',
          purple700: 'var(--base-colors-purple-purple700)',
          purple600: 'var(--base-colors-purple-purple600)',
          purple500: 'var(--base-colors-purple-purple500)',
          purple400: 'var(--base-colors-purple-purple400)',
          purple300: 'var(--base-colors-purple-purple300)',
          purple200: 'var(--base-colors-purple-purple200)',
          purple100: 'var(--base-colors-purple-purple100)',
          purple050: 'var(--base-colors-purple-purple050)',
        },
      },
      baseSize: {
        size_14: 'var(--base-size-size-14)',
        size_13: 'var(--base-size-size-13)',
        size_10: 'var(--base-size-size-10)',
        size_8: 'var(--base-size-size-8)',
        size_16: 'var(--base-size-size-16)',
        size_6: 'var(--base-size-size-6)',
        size_300: 'var(--base-size-size-300)',
        size_12: 'var(--base-size-size-12)',
        size_64: 'var(--base-size-size-64)',
        size_130: 'var(--base-size-size-130)',
        size_200: 'var(--base-size-size-200)',
        size_4: 'var(--base-size-size-4)',
        size_140: 'var(--base-size-size-140)',
        size_48: 'var(--base-size-size-48)',
        size_18: 'var(--base-size-size-18)',
        size_36: 'var(--base-size-size-36)',
        size_24: 'var(--base-size-size-24)',
        size_20: 'var(--base-size-size-20)',
        sizeRound: 'var(--base-size-size-round)',
        size_100: 'var(--base-size-size-100)',
        size_0: 'var(--base-size-size-0)',
        size_40: 'var(--base-size-size-40)',
        size_50: 'var(--base-size-size-50)',
        size_88: 'var(--base-size-size-88)',
      },
      font: {
        color: {
          primary: 'var(--font-color-primary)',
          default: 'var(--font-color-default)',
          defaultMuted: 'var(--font-color-default-muted)',
          red: 'var(--font-color-red)',
          buy: 'var(--font-color-buy)',
          sell: 'var(--font-color-sell)',
          white: 'var(--font-color-white)',
          black: 'var(--font-color-black)',
          blue: 'var(--font-color-blue)',
          footer: 'var(--font-color-footer)',
          defaultMutedDark: 'var(--font-color-default-muted-dark)',
          green: 'var(--font-color-green)',
          purple: 'var(--font-color-purple)',
        },
        size: {
          font_36: 'var(--font-size-font-36)',
          font_24: 'var(--font-size-font-24)',
          font_13: 'var(--font-size-font-13)',
          font_20: 'var(--font-size-font-20)',
          font_14: 'var(--font-size-font-14)',
          font_64: 'var(--font-size-font-64)',
          font_48: 'var(--font-size-font-48)',
          font_12: 'var(--font-size-font-12)',
          font_18: 'var(--font-size-font-18)',
          font_16: 'var(--font-size-font-16)',
          font_10: 'var(--font-size-font-10)',
        },
        lineHeights: {
          0: 'var(--font-line-heights-0)',
          1: 'var(--font-line-heights-1)',
          2: 'var(--font-line-heights-2)',
          3: 'var(--font-line-heights-3)',
          4: 'var(--font-line-heights-4)',
          5: 'var(--font-line-heights-5)',
          6: 'var(--font-line-heights-6)',
          7: 'var(--font-line-heights-7)',
          8: 'var(--font-line-heights-8)',
        },
        letterSpacing: {
          0: 'var(--font-letter-spacing-0)',
          1: 'var(--font-letter-spacing-1)',
          2: 'var(--font-letter-spacing-2)',
          3: 'var(--font-letter-spacing-3)',
          4: 'var(--font-letter-spacing-4)',
          5: 'var(--font-letter-spacing-5)',
        },
      },
      background: {
        bgDefault: 'var(--background-bg-default)',
        bgSurface: 'var(--background-bg-surface)',
        bgOutline: 'var(--background-bg-outline)',
        bgSurfaceMuted: 'var(--background-bg-surface-muted)',
        divider: 'var(--background-divider)',
        dividerMuted: 'var(--background-divider-muted)',
        bgInnerframe: 'var(--background-bg-innerframe)',
        primary: 'var(--background-primary)',
        primaryLight: 'var(--background-primary-light)',
      },
    },
  },
};
