import type { GlobalThemeOverrides } from 'naive-ui';
import {
  baseColorsPrimaryPrimary800,
  baseColorsPrimaryPrimary700,
  baseColorsPrimaryPrimaryDeep,
  baseColorsPrimaryPrimary100,
  baseColorsNeutralNeutral800,
  baseColorsNeutralNeutral500,
  baseColorsNeutralNeutral550,
  baseColorsNeutralNeutral400,
  baseColorsNeutralNeutral250,
  baseColorsNeutralNeutral000,
  fontColorDefault,
  fontColorDefaultMuted,
  fontColorDefaultMutedDark,
  inputColorTextDisable,
  inputColorSurface,
  inputColorBorderStatic,
  inputColorBorderFocus,
  inputColorBorderError,
  inputColorBorderDisabled,
  inputColorTextPlaceholder,
  inputColorTextStatic,
  inputColorBgDisabled,
  backgroundBgDefault,
  backgroundBgOutline,
  buttonPrimaryBackground,
  buttonPrimaryText,
  buttonPrimaryBorder,
  buttonOutlineBackground,
  buttonOutlineText,
  buttonOutlineBorder,
  buttonDisabledBackground,
  buttonDisabledText,
  buttonDisabledBorder,
  fontSizeFont12,
  fontSizeFont14,
  fontSizeFont16,
  fontSizeFont18,
  fontSizeFont20,
  baseSizeSize24,
  baseSizeSize13,
  baseSizeSize40,
  baseSizeSize48,
  baseSizeSize6,
  baseSizeSize16,
  baseSizeSize18,
  baseSizeSize20,
  paddingPadding4,
  paddingPadding8,
  paddingPadding12,
  paddingPadding16,
  paddingPadding24,
  paddingPadding36,
  paddingPadding48,
  radiusSm,
  radiusDefault,
  radiusMd,
  radiusLg,
  tableType1HeaderBg,
  tableType1BodyBg,
  tableType1BodyBgSelect,
  tableType1BodyBorder,
} from '../styles/_tokens-light';

export const createNaiveTheme = (): GlobalThemeOverrides => {
  return {
    common: {
      primaryColor: baseColorsPrimaryPrimary800,
      primaryColorHover: baseColorsPrimaryPrimary700,
      primaryColorPressed: baseColorsPrimaryPrimaryDeep,
      primaryColorSuppl: baseColorsPrimaryPrimary100,
      textColorBase: fontColorDefault,
      textColor1: fontColorDefault,
      textColor2: fontColorDefaultMuted,
      textColor3: fontColorDefaultMutedDark,
      textColorDisabled: inputColorTextDisable,
      bodyColor: backgroundBgDefault,
      cardColor: backgroundBgDefault,
      modalColor: backgroundBgDefault,
      popoverColor: backgroundBgDefault,
      borderColor: backgroundBgOutline,
      boxShadow1: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      boxShadow2: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      boxShadow3: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      borderRadius: radiusDefault,
      fontSize: fontSizeFont16,
      fontSizeSmall: fontSizeFont14,
      fontSizeMedium: fontSizeFont16,
      fontSizeLarge: fontSizeFont18,
      fontSizeHuge: fontSizeFont20,
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      fontFamilyMono: 'JetBrains Mono, Consolas, "Liberation Mono", Menlo, monospace',
      heightTiny: baseSizeSize24,
      heightSmall: baseSizeSize13,
      heightMedium: baseSizeSize40,
      heightLarge: baseSizeSize48,
      heightHuge: baseSizeSize6,
    },

    Button: {
      colorPrimary: buttonPrimaryBackground,
      colorPrimaryHover: baseColorsPrimaryPrimary700,
      colorPrimaryPressed: baseColorsPrimaryPrimaryDeep,
      colorPrimarySuppl: buttonPrimaryBackground,
      colorOutline: buttonOutlineBackground,
      colorOutlineHover: buttonOutlineBackground,
      colorOutlinePressed: buttonOutlineBackground,
      colorOutlineSuppl: buttonOutlineBackground,
      textColorPrimary: buttonPrimaryText,
      textColorOutline: buttonOutlineText,
      textColorDisabled: buttonDisabledText,
      borderPrimary: buttonPrimaryBorder,
      borderOutline: buttonOutlineBorder,
      borderDisabled: buttonDisabledBorder,
      heightTiny: baseSizeSize24,
      heightSmall: baseSizeSize13,
      heightMedium: baseSizeSize40,
      heightLarge: baseSizeSize48,
      heightHuge: baseSizeSize6,
      paddingTiny: `${paddingPadding4} ${paddingPadding8}`,
      paddingSmall: `${paddingPadding8} ${paddingPadding12}`,
      paddingMedium: `${paddingPadding12} ${paddingPadding16}`,
      paddingLarge: `${paddingPadding16} ${paddingPadding24}`,
      paddingHuge: `${paddingPadding24} ${paddingPadding36}`,
      fontSizeTiny: fontSizeFont12,
      fontSizeSmall: fontSizeFont14,
      fontSizeMedium: fontSizeFont16,
      fontSizeLarge: fontSizeFont18,
      fontSizeHuge: fontSizeFont20,
      borderRadiusTiny: radiusSm,
      borderRadiusSmall: radiusSm,
      borderRadiusMedium: radiusDefault,
      borderRadiusLarge: radiusMd,
      borderRadiusHuge: radiusLg,
    },

    Input: {
      color: inputColorSurface,
      colorFocus: inputColorSurface,
      colorDisabled: inputColorBgDisabled,
      border: inputColorBorderStatic,
      borderHover: inputColorBorderStatic,
      borderFocus: inputColorBorderFocus,
      borderDisabled: inputColorBorderDisabled,
      borderError: inputColorBorderError,
      textColor: inputColorTextStatic,
      textColorDisabled: inputColorTextDisable,
      placeholderColor: inputColorTextPlaceholder,
      heightTiny: baseSizeSize24,
      heightSmall: baseSizeSize13,
      heightMedium: baseSizeSize40,
      heightLarge: baseSizeSize48,
      heightHuge: baseSizeSize6,
      paddingTiny: paddingPadding4,
      paddingSmall: paddingPadding8,
      paddingMedium: paddingPadding12,
      paddingLarge: paddingPadding16,
      paddingHuge: paddingPadding24,
      fontSizeTiny: fontSizeFont12,
      fontSizeSmall: fontSizeFont14,
      fontSizeMedium: fontSizeFont16,
      fontSizeLarge: fontSizeFont18,
      fontSizeHuge: fontSizeFont20,
      borderRadiusTiny: radiusSm,
      borderRadiusSmall: radiusSm,
      borderRadiusMedium: radiusDefault,
      borderRadiusLarge: radiusMd,
      borderRadiusHuge: radiusLg,
    },

    Card: {
      color: backgroundBgDefault,
      colorModal: backgroundBgDefault,
      colorTarget: backgroundBgDefault,
      borderColor: backgroundBgOutline,
      borderColorModal: backgroundBgOutline,
      borderColorTarget: backgroundBgOutline,
      boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      boxShadowModal: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      boxShadowTarget: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      borderRadius: radiusDefault,
      borderRadiusModal: radiusMd,
      borderRadiusTarget: radiusSm,
      paddingSmall: paddingPadding12,
      paddingMedium: paddingPadding16,
      paddingLarge: paddingPadding24,
      paddingHuge: paddingPadding36,
    },

    DataTable: {
      color: tableType1BodyBg,
      colorHover: tableType1BodyBgSelect,
      colorStriped: tableType1BodyBg,
      thColor: tableType1HeaderBg,
      thColorHover: tableType1HeaderBg,
      thTextColor: fontColorDefault,
      thFontWeight: '500',
      borderColor: tableType1BodyBorder,
      thBorderColor: tableType1HeaderBg,
      tdBorderColor: tableType1BodyBorder,
      thPaddingSmall: paddingPadding8,
      thPaddingMedium: paddingPadding12,
      thPaddingLarge: paddingPadding16,
      tdPaddingSmall: paddingPadding8,
      tdPaddingMedium: paddingPadding12,
      tdPaddingLarge: paddingPadding16,
      fontSizeSmall: fontSizeFont14,
      fontSizeMedium: fontSizeFont16,
      fontSizeLarge: fontSizeFont18,
    },

    Modal: {
      color: backgroundBgDefault,
      colorMask: 'rgba(0, 0, 0, 0.45)',
      borderColor: backgroundBgOutline,
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      borderRadius: radiusMd,
      paddingSmall: paddingPadding16,
      paddingMedium: paddingPadding24,
      paddingLarge: paddingPadding36,
      paddingHuge: paddingPadding48,
    },

    Message: {
      color: backgroundBgDefault,
      colorSuccess: baseColorsNeutralNeutral250,
      colorError: baseColorsNeutralNeutral250,
      colorWarning: baseColorsNeutralNeutral550,
      colorInfo: baseColorsNeutralNeutral000,
      borderColor: backgroundBgOutline,
      borderColorSuccess: baseColorsNeutralNeutral250,
      borderColorError: baseColorsNeutralNeutral250,
      borderColorWarning: baseColorsNeutralNeutral550,
      borderColorInfo: baseColorsNeutralNeutral000,
      textColor: fontColorDefault,
      textColorSuccess: baseColorsNeutralNeutral250,
      textColorError: baseColorsNeutralNeutral250,
      textColorWarning: baseColorsNeutralNeutral550,
      textColorInfo: baseColorsNeutralNeutral000,
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      borderRadius: radiusDefault,
      padding: paddingPadding12,
    },

    Notification: {
      color: backgroundBgDefault,
      colorSuccess: baseColorsNeutralNeutral250,
      colorError: baseColorsNeutralNeutral250,
      colorWarning: baseColorsNeutralNeutral550,
      colorInfo: baseColorsNeutralNeutral000,
      borderColor: backgroundBgOutline,
      borderColorSuccess: baseColorsNeutralNeutral250,
      borderColorError: baseColorsNeutralNeutral250,
      borderColorWarning: baseColorsNeutralNeutral550,
      borderColorInfo: baseColorsNeutralNeutral000,
      textColor: fontColorDefault,
      textColorSuccess: baseColorsNeutralNeutral250,
      textColorError: baseColorsNeutralNeutral250,
      textColorWarning: baseColorsNeutralNeutral550,
      textColorInfo: baseColorsNeutralNeutral000,
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      borderRadius: radiusDefault,
      padding: paddingPadding16,
    },

    Select: {
      color: inputColorSurface,
      colorFocus: inputColorSurface,
      colorDisabled: inputColorBgDisabled,
      border: inputColorBorderStatic,
      borderHover: inputColorBorderStatic,
      borderFocus: inputColorBorderFocus,
      borderDisabled: inputColorBorderDisabled,
      borderError: inputColorBorderError,
      textColor: inputColorTextStatic,
      textColorDisabled: inputColorTextDisable,
      placeholderColor: inputColorTextPlaceholder,
      heightTiny: baseSizeSize24,
      heightSmall: baseSizeSize13,
      heightMedium: baseSizeSize40,
      heightLarge: baseSizeSize48,
      heightHuge: baseSizeSize6,
      paddingTiny: paddingPadding4,
      paddingSmall: paddingPadding8,
      paddingMedium: paddingPadding12,
      paddingLarge: paddingPadding16,
      paddingHuge: paddingPadding24,
      fontSizeTiny: fontSizeFont12,
      fontSizeSmall: fontSizeFont14,
      fontSizeMedium: fontSizeFont16,
      fontSizeLarge: fontSizeFont18,
      fontSizeHuge: fontSizeFont20,
      borderRadiusTiny: radiusSm,
      borderRadiusSmall: radiusSm,
      borderRadiusMedium: radiusDefault,
      borderRadiusLarge: radiusMd,
      borderRadiusHuge: radiusLg,
    },

    Switch: {
      color: inputColorBgDisabled,
      colorChecked: baseColorsPrimaryPrimary700,
      colorDisabled: inputColorBgDisabled,
      colorDisabledChecked: inputColorBgDisabled,
      borderColor: baseColorsPrimaryPrimary700,
      borderColorChecked: baseColorsPrimaryPrimary700,
      borderColorDisabled: inputColorBorderDisabled,
      borderColorDisabledChecked: inputColorBorderDisabled,
      width: baseSizeSize40,
      height: baseSizeSize24,
    },

    Checkbox: {
      color: baseColorsPrimaryPrimary700,
      colorChecked: baseColorsPrimaryPrimary700,
      colorDisabled: inputColorBgDisabled,
      colorDisabledChecked: inputColorBgDisabled,
      borderColor: baseColorsPrimaryPrimary700,
      borderColorChecked: baseColorsPrimaryPrimary700,
      borderColorDisabled: inputColorBorderDisabled,
      borderColorDisabledChecked: inputColorBorderDisabled,
      sizeSmall: baseSizeSize16,
      sizeMedium: baseSizeSize18,
      sizeLarge: baseSizeSize20,
    },

    Radio: {
      color: baseColorsPrimaryPrimary700,
      colorChecked: baseColorsPrimaryPrimary700,
      colorDisabled: inputColorBgDisabled,
      colorDisabledChecked: inputColorBgDisabled,
      borderColor: baseColorsPrimaryPrimary700,
      borderColorChecked: baseColorsPrimaryPrimary700,
      borderColorDisabled: inputColorBorderDisabled,
      borderColorDisabledChecked: inputColorBorderDisabled,
      sizeSmall: baseSizeSize16,
      sizeMedium: baseSizeSize18,
      sizeLarge: baseSizeSize20,
    },
  };
};
